-- SuprMorning API — add your schema here (InnoDB, utf8mb4).
-- Example when you add users + JWT refresh flow:
--
-- CREATE TABLE IF NOT EXISTS users (
--     id CHAR(36) PRIMARY KEY,
--     email VARCHAR(190) NOT NULL UNIQUE,
--     password_hash VARCHAR(255) NOT NULL,
--     role VARCHAR(50) NOT NULL DEFAULT 'user',
--     is_active TINYINT(1) NOT NULL DEFAULT 1,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
